# Generated by Django 3.1.14 on 2021-12-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_workouttype_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, verbose_name='post workout notes'),
        ),
    ]
