# Generated by Django 3.1.14 on 2021-12-12 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_auto_20211212_1306'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('performance', models.SmallIntegerField()),
                ('performedat', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.discipline')),
            ],
        ),
    ]
