# Generated by Django 3.1.14 on 2021-12-17 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_discipline_performance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performance',
            name='discipline',
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='Performance',
        ),
    ]
