# Generated by Django 3.1.14 on 2021-12-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_workouttype_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='icon',
            field=models.ImageField(default='icons/star.png', upload_to='icons/'),
        ),
    ]
