# Generated by Django 3.1.14 on 2021-12-17 08:18

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20211217_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouttype',
            name='color',
            field=colorfield.fields.ColorField(default='#DB8667', max_length=18, samples=None),
        ),
    ]
