# Generated by Django 3.1.14 on 2021-12-17 11:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0010_workouttype_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workouttype',
            name='color',
            field=colorfield.fields.ColorField(default='#DB8667', max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black')]),
        ),
    ]
